#!/usr/bin/env bash

# Run PHP-FPM as current user
if [ ! -z "$WWWUSER" ]; then
    sed -i "s/user\ \=.*/user\ \= $WWWUSER/g" /etc/php/8.0/fpm/pool.d/www.conf

    # Set UID of user "developer"
    usermod -u $WWWUSER developer
fi


    # Enable xdebug
    ## FPM
#    ln -sf /etc/php/7.4/mods-available/xdebug.ini /etc/php/7.4/fpm/conf.d/20-xdebug.ini
    ## CLI
#    ln -sf /etc/php/7.4/mods-available/xdebug.ini /etc/php/7.4/cli/conf.d/20-xdebug.ini


if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

# Run a command or supervisord
if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord
fi
